# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\qt_form\mainform.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from parse_wiki_table import start_parse

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(841, 674)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\qt_form\\../res/img/wiki.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.nameApp = QtWidgets.QLabel(self.centralwidget)
        self.nameApp.setGeometry(QtCore.QRect(40, 20, 741, 81))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.nameApp.setFont(font)
        self.nameApp.setObjectName("nameApp")
        self.url_adress = QtWidgets.QLineEdit(self.centralwidget)
        self.url_adress.setGeometry(QtCore.QRect(120, 170, 581, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.url_adress.setFont(font)
        self.url_adress.setObjectName("url_adress")
        self.buttonGetTables = QtWidgets.QPushButton(self.centralwidget)
        self.buttonGetTables.setGeometry(QtCore.QRect(280, 310, 211, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.buttonGetTables.setFont(font)
        self.buttonGetTables.setObjectName("buttonGetTables")
        self.buttonGetTables.clicked.connect(lambda : start_parse(self.url_adress.text()))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Wikipedia table parser"))
        self.nameApp.setText(_translate("MainWindow", "Wikipedia table parser"))
        self.buttonGetTables.setText(_translate("MainWindow", "Получить"))

